### PR TITLE
Fix deprecation warnings.

### PR DESCRIPTION
**Pull request by arenoir**
Change style bindings mixin to use htmlSafe().
Change deprecated attributeBindings syntzx.

### CODE REVIEW

**Comment by azirbel** [comment]
LGTM! Thanks @arenoir!

We still need to run `grunt dist` in this repository to generate the globals build. Go ahead and do that if you want, otherwise I'll just run it myself when I merge in a couple hours.

**Comment by azirbel** [comment]
@arenoir the demo application (running `ember s`) doesn't work after your change to use `htmlSafe()`. Do you know why?

**Comment by arenoir** [comment]
Oh strange; I was thinking all of the changes were pretty benign. I will look into it.

**Comment by azirbel** [comment]
Fixes applied via efa43e3ee5c6d6449b12c0886e97cf78929da13f and 9d9cd4bb5d56ff3fadb97aae1022da409aba6297.

**Pull request closed without merging**
