### PR TITLE
update to fix deprecation warnings about style bound properties

### PR DESCRIPTION
**Pull request by jimnanney**
Fix the deprecation errors.

Originally the htmlSafe was called and fixed this problem, but calling toString on the result reintroduced the problem.

### CODE REVIEW

**Comment by azirbel** [comment]
Sorry to hear that the deprecations are still there.

With this solution, the demo app doesn't run. See https://github.com/Addepar/ember-table-addon/pull/15. We'd need to fix that before merging.

**Comment by HenryVonfire** [comment]
This works for me:

styleString.toString().htmlSafe()

No deprecations and it keeps working :)

**Comment by azirbel** [comment]
@HenryVonfire if you submit that as a PR I'll merge it in.

**Comment by azirbel** [comment]
@HenryVonfire I guess I misunderstood your comment - does the demo app work for you after applying this PR?

Since we've merged `ember-table-addon` back into `ember-table`, I'm going to close this PR. I'll be happy to keep discussing if anyone opens a new PR in `ember-table`.

**Pull request closed without merging**
